dist: trusty
sudo: false

language: node_js
rvm:
  - 10.12

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --single-run --no-progress --browser=ChromeHeadlessCI
  - npm run e2e -- --no-progress --config=protractor-ci.conf.js
